apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: prometheusjmxexporters.banzaicloud.com
spec:
  group: banzaicloud.com
  names:
    kind: PrometheusJmxExporter
    listKind: PrometheusJmxExporterList
    plural: prometheusjmxexporters
    singular: prometheusjmxexporter
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-jmx-exporter-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: prometheus-jmx-exporter-operator
  template:
    metadata:
      labels:
        name: prometheus-jmx-exporter-operator
    spec:
      serviceAccountName: prometheus-jmx-exporter-operator
      containers:
        - name: prometheus-jmx-exporter-operator
          image: banzaicloud/prometheus-jmx-operator:v0.0.1
          env:
          - name: OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          command:
          - prometheus-jmx-exporter-operator
          imagePullPolicy: IfNotPresent
